version: '3'
services:
  app:
    build: .
    container_name: go-proxy
    restart: always
    networks: # ^also add here
      - default
    # environment:
      # - GOPROXY_DEBUG=1 # (optional, enable only for debug)
      # - GOPROXY_REDIRECT_HTTP=0 # (optional, uncomment to disable http redirect (http -> https))
    ports:
      - 80:80 # http
      # - 443:443 # optional, https
      - 8080:8080 # http panel
      # - 8443:8443 # optional, https panel

      # optional, if you declared any tcp/udp proxy, set a range you want to use
      # - 20000:20100/tcp
      # - 20000:20100/udp
    volumes:
      # use existing certificate
      # - /path/to/cert.pem:/app/certs/cert.crt:ro
      # - /path/to/privkey.pem:/app/certs/priv.key:ro

      # use autocert feature
      # - ./certs:/app/certs

      # if local docker provider is used (by default)
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # to use custom config and providers
      # - ./config:/app/config
    dns:
      - 127.0.0.1 # workaround for "lookup: no such host"
    extra_hosts:
      # required if you use local docker provider and have containers in `host` network_mode
      - host.docker.internal:host-gateway
    logging:
      driver: 'json-file'
      options:
        max-file: '1'
        max-size: 128k
networks: # ^you may add other external networks
  default:
    driver: bridge