version: '3'
services:
  app:
    build: .
    container_name: go-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /path/to/cert.pem:/certs/cert.crt:ro
      - /path/to/privkey.pem:/certs/priv.key:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    extra_hosts:
      - host.docker.internal:host-gateway
    logging:
      driver: 'json-file'
      options:
        max-file: '1'
        max-size: 128k
