version: '3'
services:
  app:
    build: .
    container_name: go-proxy
    hostname: go-proxy # set hostname to prevent adding itself to proxy list
    restart: always
    networks: # ^also add here
      - default
    environment:
      - VERBOSITY=1 # LOG LEVEL (optional, defaults to 1)
      - DEBUG=1 # (optional enable only for debug)
    ports:
      - 80:80 # http
      - 443:443 # https
      - 8443:8443 # panel
      - 20000:20100/tcp # tcp (optional, if you have proxy.<app>.scheme == tcp)
      - 20000:20100/udp # tcp (optional, if you have proxy.<app>.scheme == udp)
    volumes:
      - /path/to/cert.pem:/certs/cert.crt:ro
      - /path/to/privkey.pem:/certs/priv.key:ro
      - ./log:/app/log # path to logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    extra_hosts:
      - host.docker.internal:host-gateway # required if you have containers in `host` network_mode
    logging:
      driver: 'json-file'
      options:
        max-file: '1'
        max-size: 128k
networks: # ^you may add other external networks
  default:
    driver: bridge