# uncomment to use autocert
autocert: # (optional, if you need autocert feature)
  email: "user@domain.com" # (required) email for acme certificate
  domains: # (required)
    - "*.y.z" # domain for acme certificate, use wild card to allow all subdomains
  provider: cloudflare # (required) dns challenge provider (string)
  options: # provider specific options
    auth_token: "YOUR_ZONE_API_TOKEN"
providers:
  local:
    kind: docker
    # for value format, see https://docs.docker.com/reference/cli/dockerd/
    value: FROM_ENV
  # remote1:
  #   kind: docker
  #   value: ssh://user@10.0.1.1
  # remote2:
  #   kind: docker
  #   value: tcp://10.0.1.1:2375
  # provider1:
  #   kind: file
  #   value: provider1.yml
  # provider2:
  #   kind: file
  #   value: provider2.yml