# Autocert (choose one below and uncomment to enable)

# 1. use existing cert
# autocert:
#   provider: local
#   cert_path: certs/cert.crt # optional, uncomment only if you need to change it
#   key_path: certs/priv.key # optional, uncomment only if you need to change it

# 2. cloudflare
# autocert:
#   provider: cloudflare
#   email: # ACME Email
#   domains: # a list of domains for cert registration
#     - x.y.z
#   options:
#     - auth_token: c1234565789-abcdefghijklmnopqrst # your zone API token

# 3. other providers, check docs/dns_providers.md for more

providers:
  # include:
  #   - providers.yml # config/providers.yml
  #   # add some more below if you want
  #   - file1.yml # config/file_1.yml
  #   - file2.yml
  docker:
    # for value format, see https://docs.docker.com/reference/cli/dockerd/
    # $DOCKER_HOST implies unix:///var/run/docker.sock by default
    local: $DOCKER_HOST
    # add more docker providers if needed
    # remote-1: tcp://10.0.2.1:2375
    # remote-2: ssh://root:1234@10.0.2.2
# Fixed options (optional, non hot-reloadable)

# timeout_shutdown: 5
# redirect_to_https: false # redirect http requests to https (if enabled)
