theGreatPretender:
  - use: HideXForwarded
  - use: ModifyRequest
    setHeaders:
      X-Real-IP: 6.6.6.6
  - use: ModifyResponse
    hideHeaders:
      - X-Test3
      - X-Test4

notAuthenticAuthentik:
  - use: RedirectHTTP
  - use: ForwardAuth
    address: https://authentik.company
    trustForwardHeader: true
    addAuthCookiesToResponse:
      - session_id
      - user_id
    authResponseHeaders:
      - X-Auth-SessionID
      - X-Auth-UserID
  - use: CustomErrorPage

realIPAuthentik:
  - use: RedirectHTTP
  - use: RealIP
    header: X-Real-IP
    from:
      - "127.0.0.0/8"
      - "192.168.0.0/16"
      - "172.16.0.0/12"
    recursive: true
  - use: ForwardAuth
    address: https://authentik.company
    trustForwardHeader: true

testFakeRealIP:
  - use: ModifyRequest
    setHeaders:
      CF-Connecting-IP: 127.0.0.1
  - use: CloudflareRealIP
