services:
  app:
    container_name: microbin
    cpu_shares: 10
    deploy:
      resources:
        limits:
          memory: 256M
    env_file: .env
    image: danielszabo99/microbin:latest
    ports:
      - 8080
    restart: unless-stopped
    volumes:
      - ./data:/app/microbin_data
# microbin.domain.tld
