services:
  main:
    image: b3log/siyuan:v3.1.0
    container_name: siyuan
    command:
      - --workspace=/siyuan/workspace/
      - --accessAuthCode=<some password>
    user: 1000:1000
    volumes:
      - ./workspace:/siyuan/workspace
    restart: unless-stopped
    environment:
      - TZ=Asia/Hong_Kong
    ports:
      - 6806
# siyuan.domain.tld
