name: Docker Image CI

on:
  push:
    tags:
      - "*"
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Build and Push
        id: docker_build_push
        uses: GlueOps/github-actions-build-push-containers@v0.3.7
        with:
          tags: ${{ github.ref_name }}

      - name: Tag as latest
        if: startsWith(github.ref, 'refs/tags/') && !contains(github.ref_name, '-')
        run: |
          docker tag ghcr.io/${{ github.repository }}:${{ github.ref_name }} ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
